apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
        - name: websocket-service
          image: websocket-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://user-db-service:5432/userdb"